export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS'

export const GET_RECIPE_LIST_SUCCESS = 'GET_RECIPE_LIST_SUCCESS'

export const GET_RECIPE_DETAIL_SUCCESS = 'GET_RECIPE_DETAIL_SUCCESS'

export const LOAD_MORER_ECIPES_SUCCESS = 'LOAD_MORER_ECIPES_SUCCESS'

export const SEARCH_RECIPE_SUCCESS = 'SEARCH_RECIPE_SUCCESS'

export const SET_FAVORITE = 'setFavorite'

export const PRELOAD = 'PRELOAD'

export const LOADED = 'LOADED'

export const ERROR = 'ERROR'

export const PRELOAD_MORE = 'PRELOAD_MORE'

export const LOADED_MORE = 'LOADED_MORE'

